import { Router } from "express";
import { healthRouter } from "./health.route";
import { authRouter } from "./auth.route";
import { customerRouter } from "./customer.route";
import { bookingRouter } from "./booking.route";
import { branchRouter } from "./branch.route";
import { leadRouter } from "./lead.route";
import { corporateRouter } from "./corporate.route";
import { userRouter } from "./user.route";
import { agentRouter } from "./agent.route";
import { supplierRouter } from "./supplier.route";
import { catalogRouter } from "./catalog.route";
import { accountsRouter } from "./accounts.route";
import { invoicesRouter } from "./invoices.route";
import { reportsRouter } from "./reports.route";
import { documentRouter } from "./document.route";
import { notificationRouter } from "./notification.route";
import { publicRouter } from "./public.route";
import { portalRouter } from "./portal.route";
import { portalRolesRouter } from "./portal.roles.route";
import { integrationsRouter } from "./integrations.route";
import { aiRouter } from "./ai.route";
import { cmsPublicRouter } from "./cms.public.route";
import { cmsRouter } from "./cms.route";
import { communicationsRouter } from "./communications.route";
import { opsRouter } from "./ops.route";
import { receiptsRouter } from "./receipts.route";
import { systemRouter, ocrRouter } from "./system.route";
import { dashboardRouter } from "./dashboard.route";
import { partnersRouter } from "./partners.route";
import { hrRouter } from "./hr.route";

/** Aggregate API router mounted at /api. Feature routers mount here. */
export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(systemRouter);
apiRouter.use(ocrRouter);
apiRouter.use(authRouter);
apiRouter.use(customerRouter);
apiRouter.use(bookingRouter);
apiRouter.use(branchRouter);
apiRouter.use(leadRouter);
apiRouter.use(corporateRouter);
apiRouter.use(userRouter);
apiRouter.use(agentRouter);
apiRouter.use(supplierRouter);
apiRouter.use(catalogRouter);
apiRouter.use(accountsRouter);
apiRouter.use(invoicesRouter);
apiRouter.use(receiptsRouter);
apiRouter.use(reportsRouter);
apiRouter.use(documentRouter);
apiRouter.use(notificationRouter);
apiRouter.use(publicRouter);
apiRouter.use(cmsPublicRouter);
apiRouter.use(cmsRouter);
apiRouter.use(portalRouter);
apiRouter.use(portalRolesRouter);
apiRouter.use(integrationsRouter);
apiRouter.use(aiRouter);
apiRouter.use(communicationsRouter);
apiRouter.use(opsRouter);
apiRouter.use(dashboardRouter);
apiRouter.use(partnersRouter);
apiRouter.use(hrRouter);
