/**
 * Islamic Guidance Center — editorial content (no CMS model).
 * Bangla-first copy with English fallbacks for the language switch.
 */
export interface GuideFaq { q: string; a: string }
export interface GuideContent {
  slug: string;
  icon: string;
  category: "ritual" | "checklist" | "rules" | "docs";
  titleBn: string;
  titleEn: string;
  summaryBn: string;
  summaryEn: string;
  duaAr?: string;
  duaBn?: string;
  explanationBn: string;
  explanationEn: string;
  quran?: { ref: string; textBn: string; textEn: string }[];
  hadith?: { ref: string; textBn: string; textEn: string }[];
  stepsBn: string[];
  stepsEn: string[];
  doBn: string[];
  doEn: string[];
  dontBn: string[];
  dontEn: string[];
  faqs: GuideFaq[];
  relatedVideos?: string[];
  nextSlug?: string;
  image: string;
}

const G = (
  partial: GuideContent,
): GuideContent => partial;

export const GUIDES: GuideContent[] = [
  G({
    slug: "what-is-ihram",
    icon: "Shirt",
    category: "ritual",
    titleBn: "ইহরাম কী?",
    titleEn: "What is Ihram",
    summaryBn: "ইহরাম হজ্ব ও উমরাহর পবিত্র অবস্থা এবং বিশেষ পোশাক।",
    summaryEn: "Ihram is the sacred state and garments for Hajj and Umrah.",
    duaAr: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ",
    duaBn: "লাব্বাইক আল্লাহুম্মা লাব্বাইক",
    explanationBn: "ইহরাম হলো সেই পবিত্র অবস্থা যেখানে হাজি বা মুতামির নির্দিষ্ট নিয়ম মেনে হজ্ব বা উমরাহ শুরু করেন। পুরুষদের জন্য সাদা দুই কাপড় এবং নারীদের জন্য শালীন পোশাক।",
    explanationEn: "Ihram is the sacred state in which a pilgrim begins Hajj or Umrah, observing specific rules. Men wear two white unstitched cloths; women wear modest clothing.",
    quran: [{ ref: "সূরা আল-বাকারা ২:১৯৬", textBn: "আর আল্লাহর জন্য হজ্ব ও উমরাহ পূর্ণ করো।", textEn: "And complete the Hajj and Umrah for Allah." }],
    hadith: [{ ref: "বুখারী ও মুসলিম", textBn: "হজ্বের আমল ইহরাম বাঁধার মাধ্যমে শুরু হয়।", textEn: "The rites of pilgrimage begin with entering Ihram." }],
    stepsBn: ["নিয়ত করুন", "গোসল ও পবিত্রতা", "ইহরামের কাপড় পরুন", "তালবিয়া পাঠ করুন", "মিবাতে পৌঁছান"],
    stepsEn: ["Make intention", "Purify yourself", "Wear Ihram", "Recite Talbiyah", "Proceed to Miqat"],
    doBn: ["পবিত্রতা রক্ষা করুন", "তালবিয়া বেশি পড়ুন", "ধৈর্য ধরুন"],
    doEn: ["Maintain purity", "Recite Talbiyah often", "Be patient"],
    dontBn: ["সুগন্ধি ব্যবহার", "মাথা ঢাকা (পুরুষ)", "শিকার করা"],
    dontEn: ["Use perfume", "Cover the head (men)", "Hunt"],
    faqs: [
      { q: "ইহরাম কখন বাঁধতে হয়?", a: "মিবাত পার হওয়ার আগে নিয়ত ও তালবিয়ার সাথে ইহরাম বাঁধতে হয়।" },
      { q: "নারীরা কি সাদা কাপড় পরবেন?", a: "না, নারীদের জন্য নির্দিষ্ট সাদা কাপড় বাধ্যতামূলক নয়; শালীন পোশাক যথেষ্ট।" },
    ],
    relatedVideos: ["v6", "v2"],
    nextSlug: "how-to-wear-ihram",
    image: "photo-1564769625905-50e93615e769",
  }),
  G({
    slug: "how-to-wear-ihram",
    icon: "Layers",
    category: "ritual",
    titleBn: "ইহরাম কিভাবে পরবেন",
    titleEn: "How to Wear Ihram",
    summaryBn: "পুরুষদের দুই কাপড় পরার সঠিক পদ্ধতি।",
    summaryEn: "The correct way for men to wear the two cloths.",
    explanationBn: "একটি কাপড় কোমরে জড়ানো হয় এবং অন্যটি কাঁধে রাখা হয়। নাভির নিচ থেকে হাঁটু ঢেকে রাখতে হবে।",
    explanationEn: "One cloth wraps the waist; the other covers the shoulders. Cover from navel to knees.",
    stepsBn: ["গোসল করুন", "নিচের কাপড় বাঁধুন", "উপরের কাপড় পরুন", "চপ্পল পরুন", "নিয়ত ও তালবিয়া"],
    stepsEn: ["Bathe", "Wrap lower cloth", "Drape upper cloth", "Wear sandals", "Intention & Talbiyah"],
    doBn: ["আরামদায়ক বাঁধুন", "পরিষ্কার কাপড় ব্যবহার করুন"],
    doEn: ["Wrap securely", "Use clean cloths"],
    dontBn: ["সেলাই করা পোশাক", "মোজা (পুরুষ)"],
    dontEn: ["Stitched garments", "Socks (men)"],
    faqs: [{ q: "বেল্ট ব্যবহার করা যায়?", a: "ইহরাম ধরে রাখতে সাধারণ বেল্ট বা কোমরবন্ধ ব্যবহার করা যায়।" }],
    nextSlug: "intention-niyyah",
    image: "photo-1591604129939-f1efa4d9f7fa",
  }),
  G({
    slug: "intention-niyyah",
    icon: "Heart",
    category: "ritual",
    titleBn: "নিয়্যত (Intention)",
    titleEn: "Intention (Niyyah)",
    summaryBn: "হৃদয়ে নিয়ত হজ্ব বা উমরাহর মূল শর্ত।",
    summaryEn: "Intention in the heart is essential for Hajj or Umrah.",
    duaAr: "لَبَّيْكَ اللَّهُمَّ عُمْرَةً",
    duaBn: "লাব্বাইক আল্লাহুম্মা উমরাতান",
    explanationBn: "নিয়ত মনে মনেই যথেষ্ট; মুখে বলা মুস্তাহাব। হজ্ব, উমরাহ বা কিরান অনুযায়ী নিয়ত ভিন্ন হয়।",
    explanationEn: "Intention in the heart is sufficient; saying it aloud is recommended. Wording differs for Hajj, Umrah, or Qiran.",
    stepsBn: ["উদ্দেশ্য স্থির করুন", "মিবাতে নিয়ত করুন", "তালবিয়া শুরু করুন"],
    stepsEn: ["Clarify purpose", "Intend at Miqat", "Begin Talbiyah"],
    doBn: ["আন্তরিকতা রাখুন", "শুধু আল্লাহর জন্য"],
    doEn: ["Be sincere", "For Allah alone"],
    dontBn: ["লোক দেখানো নিয়ত", "সংশয়"],
    dontEn: ["Showing off", "Doubt"],
    faqs: [{ q: "নিয়ত ভুলে গেলে?", a: "হৃদয়ে উদ্দেশ্য থাকলেই যথেষ্ট; সন্দেহ হলে পুনরায় নিয়ত করুন।" }],
    nextSlug: "talbiyah",
    image: "photo-1519817650395-5d7d17a4a4c5",
  }),
  G({
    slug: "talbiyah",
    icon: "Mic",
    category: "ritual",
    titleBn: "তালবিয়া",
    titleEn: "Talbiyah",
    summaryBn: "ইহরামের পর আল্লাহর ডাকে সাড়া দেওয়ার ধ্বনি।",
    summaryEn: "The response to Allah’s call after entering Ihram.",
    duaAr: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ",
    duaBn: "লাব্বাইক আল্লাহুম্মা লাব্বাইক, লাব্বাইক লা শারিকা লাকা লাব্বাইক",
    explanationBn: "তালবিয়া ইহরাম থেকে তাওয়াফ শুরু পর্যন্ত পড়া হয়। পুরুষরা জোরে, নারীরা নিঃশব্দে পড়েন।",
    explanationEn: "Talbiyah is recited from Ihram until Tawaf begins. Men recite aloud; women softly.",
    stepsBn: ["ইহরামের পর শুরু", "যাত্রাপথে বারবার পড়ুন", "তাওয়াফ শুরুতে বন্ধ"],
    stepsEn: ["Start after Ihram", "Repeat on the journey", "Stop when Tawaf begins"],
    doBn: ["অধিক পড়ুন", "অর্থ বুঝে পড়ুন"],
    doEn: ["Recite often", "Understand the meaning"],
    dontBn: ["অন্য গান/ধ্বনি মিলিয়ে", "অশালীন উচ্চস্বরে"],
    dontEn: ["Mix with other chants", "Disturbing loudness"],
    faqs: [{ q: "তালবিয়া কখন বন্ধ?", a: "উমরাহর তাওয়াফ শুরু করলে তালবিয়া বন্ধ হয়।" }],
    nextSlug: "tawaf",
    image: "photo-1564769625905-50e93615e769",
  }),
  G({
    slug: "tawaf",
    icon: "RefreshCw",
    category: "ritual",
    titleBn: "তাওয়াফ",
    titleEn: "Tawaf",
    summaryBn: "কাবার চারপাশে সাতবার প্রদক্ষিণ।",
    summaryEn: "Seven circuits around the Kaaba.",
    explanationBn: "হাজরে আসওয়াদ থেকে শুরু করে কাবাকে বামে রেখে সাত চক্কর সম্পন্ন করতে হয়। প্রতি চক্করে দোয়া পড়া যায়।",
    explanationEn: "Starting from the Black Stone, keep the Kaaba on your left and complete seven circuits. Duas may be recited each lap.",
    stepsBn: ["উযূ করুন", "হাজরে আসওয়াদের দিকে মুখ", "সাত চক্কর", "মাকামে ইব্রাহিমে সালাত", "জমজম পান"],
    stepsEn: ["Perform wudu", "Face Black Stone", "Seven circuits", "Pray at Maqam Ibrahim", "Drink Zamzam"],
    doBn: ["ধৈর্য ও শান্তি", "অন্যের জায়গা দিন"],
    doEn: ["Stay calm", "Give others space"],
    dontBn: ["ধাক্কাধাক্কি", "ফোন দিয়ে লাইভ অতিরিক্ত"],
    dontEn: ["Pushing", "Excessive live streaming"],
    faqs: [{ q: "রমলে কখন?", a: "উমরাহর প্রথম তাওয়াফে পুরুষরা প্রথম তিন চক্করে রমল করেন।" }],
    nextSlug: "sai",
    image: "photo-1564769625905-50e93615e769",
  }),
  G({
    slug: "sai",
    icon: "Footprints",
    category: "ritual",
    titleBn: "সাঈ",
    titleEn: "Sa'i",
    summaryBn: "সাফা ও মারওয়ার মধ্যে সাতবার যাতায়াত।",
    summaryEn: "Seven traversals between Safa and Marwah.",
    explanationBn: "হাজেরা (আ.)-এর স্মরণে সাফা থেকে মারওয়া পর্যন্ত সাঈ করা হয়। সবুজ আলোকিত অংশে পুরুষরা দৌড়ান।",
    explanationEn: "Sa'i commemorates Hajar (AS) between Safa and Marwah. Men jog in the green-lit section.",
    stepsBn: ["সাফায় আরোহণ ও দোয়া", "মারওয়া পর্যন্ত যান", "সাত চক্কর পূর্ণ", "চুল ছাঁটা/ক্ষৌর"],
    stepsEn: ["Ascend Safa & dua", "Walk to Marwah", "Complete seven", "Trim/shave hair"],
    doBn: ["ধীরস্থির চলুন", "পানি সাথে রাখুন"],
    doEn: ["Walk steadily", "Carry water"],
    dontBn: ["ভিড়ের মধ্যে দৌড়ানো নারীদের জন্য", "সাঈ বাদ দেওয়া"],
    dontEn: ["Women running in crowd", "Skipping Sa'i"],
    faqs: [{ q: "হুইলচেয়ার কি চলবে?", a: "হ্যাঁ, প্রয়োজনে হুইলচেয়ার বা গাড়ি ব্যবহার করা যায়।" }],
    nextSlug: "mina",
    image: "photo-1591604129939-f1efa4d9f7fa",
  }),
  G({
    slug: "mina",
    icon: "Tent",
    category: "ritual",
    titleBn: "মিনা",
    titleEn: "Mina",
    summaryBn: "হজ্বের তাশরিকের দিনগুলোর অবস্থান।",
    summaryEn: "The stay during the days of Tashreeq.",
    explanationBn: "৮ জিলহজ মিনায় অবস্থান মুস্তাহাব। ১০–১৩ তারিখে জামারাত নিক্ষেপের ভিত্তি এখান থেকে।",
    explanationEn: "Staying in Mina on 8 Dhul-Hijjah is recommended. Stoning of the Jamarat on 10–13 is based from here.",
    stepsBn: ["৮ তারিখ মিনায় যান", "নামাজ আদায়", "আরাফাতের প্রস্তুতি", "তাশরিকের রাত"],
    stepsEn: ["Go to Mina on 8th", "Pray the prayers", "Prepare for Arafat", "Nights of Tashreeq"],
    doBn: ["তাঁবুতে শৃঙ্খলা", "পরস্পরকে সাহায্য"],
    doEn: ["Keep tent orderly", "Help others"],
    dontBn: ["অবৈধ আগুন", "আবর্জনা ফেলা"],
    dontEn: ["Unsafe fires", "Littering"],
    faqs: [{ q: "মিনায় কতদিন?", a: "সাধারণত ৮ থেকে ১২/১৩ জিলহজ পর্যন্ত, প্যাকেজ অনুযায়ী।" }],
    nextSlug: "arafat",
    image: "photo-1519817650395-5d7d17a4a4c5",
  }),
  G({
    slug: "arafat",
    icon: "Sunrise",
    category: "ritual",
    titleBn: "আরাফাত",
    titleEn: "Arafat",
    summaryBn: "হজ্বের মূল রুকন — ওয়ুকুফে আরাফা।",
    summaryEn: "The essential pillar — standing at Arafat.",
    duaAr: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    explanationBn: "৯ জিলহজ সূর্যাস্ত পর্যন্ত আরাফাতে অবস্থান হজ্বের সবচেয়ে গুরুত্বপূর্ণ আমল। দোয়া, জিকির ও তাওবা করুন।",
    explanationEn: "Standing at Arafat until sunset on 9 Dhul-Hijjah is the most important rite. Make dua, dhikr, and repentance.",
    stepsBn: ["সকালে আরাফাত", "জোহর-আসর জমা", "দোয়ায় মশগুল", "সূর্যাস্তের পর মুজদালিফা"],
    stepsEn: ["Arrive morning", "Combine Zuhr-Asr", "Engage in dua", "Leave after sunset"],
    doBn: ["অধিক দোয়া", "সিয়াম না রাখা (অধিকাংশের জন্য)"],
    doEn: ["Abundant dua", "Usually not fasting"],
    dontBn: ["সূর্যাস্তের আগে ছাড়া", "অযথা ভিডিও"],
    dontEn: ["Leaving before sunset", "Needless filming"],
    faqs: [{ q: "আরাফাত মিস হলে?", a: "ওয়ুকুফ মিস হলে সেই বছরের হজ্ব পূর্ণ হয় না — তাই সময় মেনে চলুন।" }],
    nextSlug: "muzdalifah",
    image: "photo-1564769625905-50e93615e769",
  }),
  G({
    slug: "muzdalifah",
    icon: "Moon",
    category: "ritual",
    titleBn: "মুজদালিফা",
    titleEn: "Muzdalifah",
    summaryBn: "আরাফাতের পর রাতযাপন ও কংকর সংগ্রহ।",
    summaryEn: "Overnight stay and collecting pebbles after Arafat.",
    explanationBn: "মাগরিব-ইশা একত্রে পড়ে রাত কাটানো হয়। এখান থেকে জামারাতের কংকর সংগ্রহ করা যায়।",
    explanationEn: "Pray Maghrib and Isha combined and spend the night. Pebbles for Jamarat may be collected here.",
    stepsBn: ["আরাফাত থেকে আসুন", "মাগরিব-ইশা", "বিশ্রাম", "ফজরের পর মিনা"],
    stepsEn: ["Arrive from Arafat", "Maghrib-Isha", "Rest", "To Mina after Fajr"],
    doBn: ["হালকা মালামাল", "পরিবারের খেয়াল"],
    doEn: ["Travel light", "Care for family"],
    dontBn: ["অপ্রয়োজনীয় আগুন", "রাতভর শোরগোল"],
    dontEn: ["Unnecessary fires", "All-night noise"],
    faqs: [{ q: "দুর্বলরা কি আগে যেতে পারে?", a: "নারী, বৃদ্ধ ও দুর্বলদের জন্য অর্ধরাতে চলে যাওয়ার অনুমতি আছে।" }],
    nextSlug: "ramy",
    image: "photo-1591604129939-f1efa4d9f7fa",
  }),
  G({
    slug: "ramy",
    icon: "Target",
    category: "ritual",
    titleBn: "রমী (জামারাত)",
    titleEn: "Ramy",
    summaryBn: "শয়তানের প্রতীক জামারাতে কংকর নিক্ষেপ।",
    summaryEn: "Stoning the Jamarat pillars.",
    explanationBn: "১০ তারিখে শুধু বড় জামারা, পরের দিনগুলোতে তিনটি। নিরাপত্তা ও সময়সূচি মেনে চলুন।",
    explanationEn: "On the 10th only the large Jamrah; then all three on following days. Follow safety and schedules.",
    stepsBn: ["কংকর প্রস্তুত", "সঠিক জামারা", "একক নিক্ষেপ", "দোয়া (প্রথম দুটিতে)"],
    stepsEn: ["Prepare pebbles", "Correct Jamrah", "Throw individually", "Dua after first two"],
    doBn: ["ধৈর্য", "অফ-পিক সময়"],
    doEn: ["Patience", "Off-peak times"],
    dontBn: ["বড় পাথর", "ধাক্কাধাক্কি"],
    dontEn: ["Large stones", "Pushing"],
    faqs: [{ q: "প্রক্সি রমী?", a: "অক্ষম ব্যক্তির পক্ষে অন্য কেউ নিক্ষেপ করতে পারে।" }],
    nextSlug: "qurbani",
    image: "photo-1519817650395-5d7d17a4a4c5",
  }),
  G({
    slug: "qurbani",
    icon: "Beef",
    category: "ritual",
    titleBn: "কুরবানি",
    titleEn: "Qurbani",
    summaryBn: "হজ্বে দম/হাদী হিসেবে পশু উৎসর্গ।",
    summaryEn: "Sacrificial offering (Hady) during Hajj.",
    explanationBn: "তামাত্তু ও কিরান হজ্বে কুরবানি ওয়াজিব। অনেক প্যাকেজে ভাউচারের মাধ্যমে সম্পন্ন হয়।",
    explanationEn: "Sacrifice is obligatory in Tamattu and Qiran. Many packages complete it via vouchers.",
    stepsBn: ["প্যাকেজ/ভাউচার নিশ্চিত", "১০ তারিখের পর", "হালক করা/ক্ষৌর"],
    stepsEn: ["Confirm package/voucher", "After 10th", "Trim/shave"],
    doBn: ["হালাল নিশ্চিত করুন", "রসিদ রাখুন"],
    doEn: ["Ensure halal", "Keep receipt"],
    dontBn: ["অনিশ্চিত ব্যবসায়ী", "বাধ্যতা এড়িয়ে যাওয়া"],
    dontEn: ["Unverified vendors", "Skipping if required"],
    faqs: [{ q: "একক হজ্বে কুরবানি?", a: "ইফরাদে বাধ্যতামূলক নয়, তবে নফল করা যায়।" }],
    nextSlug: "hair-cutting",
    image: "photo-1540962351504-03099e0a754b",
  }),
  G({
    slug: "hair-cutting",
    icon: "Scissors",
    category: "ritual",
    titleBn: "চুল কাটা / ক্ষৌর",
    titleEn: "Hair Cutting",
    summaryBn: "উমরাহ বা হজ্বের পর তাহাল্লুল।",
    summaryEn: "Halq or Taqsir to exit Ihram.",
    explanationBn: "পুরুষদের জন্য মাথা মুণ্ডন উত্তম; নারীরা আঙুল পরিমাণ চুল কাটেন।",
    explanationEn: "Shaving is preferred for men; women cut a fingertip length of hair.",
    stepsBn: ["সাঈ/রমীর পর", "ক্ষৌর বা ছাঁটাই", "ইহরাম খুলুন"],
    stepsEn: ["After Sa'i/Ramy", "Shave or trim", "Exit Ihram"],
    doBn: ["পবিত্র স্থান ব্যবহার", "নারীদের গোপনীয়তা"],
    doEn: ["Use clean facilities", "Women’s privacy"],
    dontBn: ["আংশিক অসম কাটা পুরুষদের", "অন্যের চুল কাটা জোর করে"],
    dontEn: ["Uneven partial shave for men", "Forcing others"],
    faqs: [{ q: "মেশিন ব্যবহার?", a: "হ্যাঁ, ক্ষৌর বা ছাঁটাই মেশিনে করা যায়।" }],
    nextSlug: "farewell-tawaf",
    image: "photo-1564769625905-50e93615e769",
  }),
  G({
    slug: "farewell-tawaf",
    icon: "DoorOpen",
    category: "ritual",
    titleBn: "বিদায়ী তাওয়াফ",
    titleEn: "Farewell Tawaf",
    summaryBn: "মক্কা ছাড়ার আগে শেষ তাওয়াফ।",
    summaryEn: "The final Tawaf before leaving Makkah.",
    explanationBn: "তাওয়াফে বিদা (বিদায়ী তাওয়াফ) মক্কা ত্যাগের আগে আদায় করা হয়। হায়েজ অবস্থায় নারীদের জন্য ছাড় আছে।",
    explanationEn: "Tawaf al-Wada is performed before leaving Makkah. Women in menstruation are excused.",
    stepsBn: ["যাত্রার কাছাকাছি সময়ে", "সাত চক্কর", "মক্কা ছাড়ুন"],
    stepsEn: ["Close to departure", "Seven circuits", "Leave Makkah"],
    doBn: ["ভারী মাল আগে পাঠান", "সময় রাখুন"],
    doEn: ["Send luggage ahead", "Allow time"],
    dontBn: ["তাওয়াফের পর দোকানে দেরি", "বাদ দেওয়া (ছাড় ছাড়া)"],
    dontEn: ["Long shopping after", "Skipping without excuse"],
    faqs: [{ q: "মদিনা গেলে?", a: "মক্কা থেকে চূড়ান্তভাবে বেরোনোর আগেই বিদায়ী তাওয়াফ করুন।" }],
    nextSlug: "womens-rules",
    image: "photo-1591604129939-f1efa4d9f7fa",
  }),
  G({
    slug: "womens-rules",
    icon: "HeartHandshake",
    category: "rules",
    titleBn: "নারীদের নিয়মাবলি",
    titleEn: "Women's Rules",
    summaryBn: "ইহরাম, তাওয়াফ ও সফরে নারীদের বিশেষ বিধান।",
    summaryEn: "Special rulings for women in Ihram, Tawaf, and travel.",
    explanationBn: "নারীরা মুখ ও হাত ঢাকতে পারেন (নিষিদ্ধ নিয়াব/গ্লাভস ইহরামে নয় — মতামতভেদ আছে; স্থানীয় আলেমের পরামর্শ নিন)। হায়েজে তাওয়াফ বিলম্বিত হয়।",
    explanationEn: "Women wear modest dress; face/hand coverings have scholarly nuances—consult a scholar. Menstruation delays Tawaf.",
    stepsBn: ["মাহরাম নিশ্চিত", "শালীন পোশাক", "হায়েজ পরিকল্পনা", "ভিড়ে সতর্কতা"],
    stepsEn: ["Ensure mahram", "Modest dress", "Plan for menses", "Crowd safety"],
    doBn: ["গোপনীয়তা", "সহজ জুতা"],
    doEn: ["Privacy", "Comfortable shoes"],
    dontBn: ["একা বিপজ্জনক ভিড়", "অতিরিক্ত সুগন্ধি"],
    dontEn: ["Unsafe alone in crowds", "Heavy perfume"],
    faqs: [{ q: "হায়েজে সাঈ?", a: "সাঈর আগে তাওয়াফ প্রয়োজন; হায়েজে তাওয়াফ পরে করা হয়।" }],
    nextSlug: "things-that-break-ihram",
    image: "photo-1519817650395-5d7d17a4a4c5",
  }),
  G({
    slug: "things-that-break-ihram",
    icon: "Ban",
    category: "rules",
    titleBn: "যা ইহরাম ভঙ্গ করে",
    titleEn: "Things That Break Ihram",
    summaryBn: "নিষিদ্ধ কাজ ও সম্ভাব্য কাফফারা।",
    summaryEn: "Prohibitions and possible expiation.",
    explanationBn: "সুগন্ধি, চুল/নখ কাটা, সেলাই পোশাক (পুরুষ), দাম্পত্য সম্পর্ক ইত্যাদি নিষিদ্ধ। ভুল হলে আলেমের পরামর্শে কাফফারা।",
    explanationEn: "Perfume, cutting hair/nails, stitched clothes (men), intimacy, etc. are forbidden. Mistakes may require expiation—ask a scholar.",
    stepsBn: ["নিষেধাজ্ঞা জানুন", "সন্দেহে জিজ্ঞাসা", "প্রয়োজনে দম"],
    stepsEn: ["Know prohibitions", "Ask when unsure", "Offer expiation if needed"],
    doBn: ["সতর্ক থাকুন", "গ্রুপ গাইডকে জানান"],
    doEn: ["Stay cautious", "Inform group guide"],
    dontBn: ["ইচ্ছাকৃত লঙ্ঘন", "গোপন রাখা"],
    dontEn: ["Deliberate violation", "Hiding mistakes"],
    faqs: [{ q: "সাবান কি নিষিদ্ধ?", a: "সুগন্ধযুক্ত সাবান এড়িয়ে চলুন; গন্ধহীন ব্যবহার করা যায়।" }],
    nextSlug: "common-mistakes",
    image: "photo-1540962351504-03099e0a754b",
  }),
  G({
    slug: "common-mistakes",
    icon: "AlertTriangle",
    category: "rules",
    titleBn: "সাধারণ ভুলসমূহ",
    titleEn: "Common Mistakes",
    summaryBn: "হজ্ব-উমরাহর প্রায়শই ঘটে যাওয়া ভুল।",
    summaryEn: "Frequent mistakes during Hajj and Umrah.",
    explanationBn: "মিবাত পার হয়ে ইহরাম না বাঁধা, তাওয়াফে ভুল গণনা, আরাফাত তাড়াতাড়ি ছাড়া — এগুলো এড়ান।",
    explanationEn: "Crossing Miqat without Ihram, miscounting Tawaf, leaving Arafat early—avoid these.",
    stepsBn: ["প্রশিক্ষণ নিন", "চেকলিস্ট ব্যবহার", "গাইড অনুসরণ"],
    stepsEn: ["Take training", "Use checklists", "Follow guide"],
    doBn: ["প্রশ্ন করুন", "নোট রাখুন"],
    doEn: ["Ask questions", "Keep notes"],
    dontBn: ["গুজব অনুসরণ", "তাড়াহুড়ো"],
    dontEn: ["Follow rumors", "Rushing"],
    faqs: [{ q: "তাওয়াফ গণনা ভুল?", a: "সন্দেহ হলে কম সংখ্যা ধরে পূর্ণ করুন।" }],
    nextSlug: "packing-checklist",
    image: "photo-1469854523086-cc02fe5d8800",
  }),
  G({
    slug: "packing-checklist",
    icon: "Backpack",
    category: "checklist",
    titleBn: "প্যাকিং চেকলিস্ট",
    titleEn: "Packing Checklist",
    summaryBn: "হজ্ব-উমরাহর জন্য প্রয়োজনীয় জিনিসপত্র।",
    summaryEn: "Essential items for Hajj and Umrah.",
    explanationBn: "ইহরাম, ওষুধ, চarger, হালকা পোশাক, মসজিদের ব্যাগ ও নথি আলাদা রাখুন।",
    explanationEn: "Pack Ihram, medicines, chargers, light clothes, prayer bag, and keep documents separate.",
    stepsBn: ["নথি পোর্চ", "ইহরাম ২ সেট", "ওষুধ", "পাওয়ার ব্যাংক", "মোজা/চপ্পল"],
    stepsEn: ["Document pouch", "2 Ihram sets", "Medicine", "Power bank", "Sandals"],
    doBn: ["হালকা ব্যাগ", "নাম ট্যাগ"],
    doEn: ["Pack light", "Name tags"],
    dontBn: ["অতিরিক্ত তরল", "নিষিদ্ধ দ্রব্য"],
    dontEn: ["Excess liquids", "Prohibited items"],
    faqs: [{ q: "সুটকেস সাইজ?", a: "এয়ারলাইনস ফ্রি ব্যাগেজ অনুযায়ী; কেবিনে জরুরি জিনিস রাখুন।" }],
    nextSlug: "medical-checklist",
    image: "photo-1436491865332-7a61a109cc05",
  }),
  G({
    slug: "medical-checklist",
    icon: "HeartPulse",
    category: "checklist",
    titleBn: "মেডিকেল চেকলিস্ট",
    titleEn: "Medical Checklist",
    summaryBn: "স্বাস্থ্য পরীক্ষা, টিকা ও ওষুধ।",
    summaryEn: "Health checks, vaccines, and medicines.",
    explanationBn: "ডাক্তারের পরামর্শ, প্রয়োজনীয় প্রেসক্রিপশন ও টিকা কার্ড সাথে রাখুন।",
    explanationEn: "See a doctor, carry prescriptions and vaccination cards.",
    stepsBn: ["চেকআপ", "টিকা", "ওষুধ তালিকা", "বীমা"],
    stepsEn: ["Checkup", "Vaccines", "Medicine list", "Insurance"],
    doBn: ["পর্যাপ্ত পানি", "বিশ্রাম"],
    doEn: ["Hydrate", "Rest"],
    dontBn: ["অপরিচিত ওষুধ", "উপেক্ষা করা উপসর্গ"],
    dontEn: ["Unknown medicines", "Ignoring symptoms"],
    faqs: [{ q: "মেনিনজাইটিস টিকা?", a: "সৌদি হজ্ব/উমরাহর জন্য সাধারণত বাধ্যতামূলক — হালনাগাদ নিয়ম দেখুন।" }],
    nextSlug: "travel-checklist",
    image: "photo-1454165804606-c3d57bc86b40",
  }),
  G({
    slug: "travel-checklist",
    icon: "Plane",
    category: "checklist",
    titleBn: "ভ্রমণ চেকলিস্ট",
    titleEn: "Travel Checklist",
    summaryBn: "ফ্লাইট, হোটেল ও গ্রুপ সমন্বয়।",
    summaryEn: "Flights, hotels, and group coordination.",
    explanationBn: "বোর্ডিং পাস, গ্রুপ চ্যাট, হোটেল ভাউচার ও জরুরি নম্বর সংরক্ষণ করুন।",
    explanationEn: "Save boarding passes, group chat, hotel vouchers, and emergency numbers.",
    stepsBn: ["ফ্লাইট চেক-ইন", "গ্রুপ মিটিং পয়েন্ট", "সিম/রোমিং", "মুদ্রা"],
    stepsEn: ["Flight check-in", "Meeting point", "SIM/roaming", "Currency"],
    doBn: ["অনলাইন চেক-ইন", "পারিবারিক পরিকল্পনা"],
    doEn: ["Online check-in", "Family plan"],
    dontBn: ["শেষ মুহূর্তের কেনাকাটা", "পাসপোর্ট আলাদা রাখা"],
    dontEn: ["Last-minute shopping rushes", "Separating passport carelessly"],
    faqs: [{ q: "এয়ারপোর্টে কত আগে?", a: "আন্তর্জাতিক ফ্লাইটে সাধারণত ৩–৪ ঘণ্টা আগে পৌঁছান।" }],
    nextSlug: "visa-preparation",
    image: "photo-1436491865332-7a61a109cc05",
  }),
  G({
    slug: "visa-preparation",
    icon: "Stamp",
    category: "docs",
    titleBn: "ভিসা প্রস্তুতি",
    titleEn: "Visa Preparation",
    summaryBn: "হজ্ব/উমরাহ/ভিজিট ভিসার কাগজপত্র।",
    summaryEn: "Documents for Hajj, Umrah, or visit visas.",
    explanationBn: "পাসপোর্ট, ছবি, টিকা, ফর্ম ও এজেন্সি নির্দেশনা সময়মতো জমা দিন।",
    explanationEn: "Submit passport, photos, vaccines, forms, and agency instructions on time.",
    stepsBn: ["পাসপোর্ট চেক", "ছবি স্পেক", "ফর্ম পূরণ", "বায়োমেট্রিক"],
    stepsEn: ["Passport check", "Photo specs", "Fill forms", "Biometrics"],
    doBn: ["কপি রাখুন", "ডেডলাইন মানুন"],
    doEn: ["Keep copies", "Meet deadlines"],
    dontBn: ["মেয়াদোত্তীর্ণ পাসপোর্ট", "মিথ্যা তথ্য"],
    dontEn: ["Expired passport", "False information"],
    faqs: [{ q: "কতদিন লাগে?", a: "ভিসার ধরন ও সিজন অনুযায়ী ভিন্ন — এজেন্সির আপডেট অনুসরণ করুন।" }],
    nextSlug: "passport-requirements",
    image: "photo-1540962351504-03099e0a754b",
  }),
  G({
    slug: "passport-requirements",
    icon: "BookOpen",
    category: "docs",
    titleBn: "পাসপোর্ট শর্তাবলি",
    titleEn: "Passport Requirements",
    summaryBn: "মেয়াদ, খালি পৃষ্ঠা ও নাম মিল।",
    summaryEn: "Validity, blank pages, and name matching.",
    explanationBn: "সাধারণত ভ্রমণের পর কমপক্ষে ৬ মাস মেয়াদ এবং খালি পৃষ্ঠা প্রয়োজন।",
    explanationEn: "Usually at least 6 months validity beyond travel and blank pages are required.",
    stepsBn: ["মেয়াদ দেখুন", "নবায়ন", "নাম মিলান", "স্ক্যান কপি"],
    stepsEn: ["Check expiry", "Renew", "Match names", "Scanned copies"],
    doBn: ["ডিজিটাল কপি", "প্লাস্টিক কভার"],
    doEn: ["Digital copies", "Protective cover"],
    dontBn: ["ক্ষতিগ্রস্ত পাসপোর্ট", "অন্যের পাসপোর্ট"],
    dontEn: ["Damaged passport", "Someone else’s passport"],
    faqs: [{ q: "মেশিন রিডেবল?", a: "আধুনিক ই-পাসপোর্ট বাধ্যতামূলক হতে পারে — স্থানীয় অফিস যাচাই করুন।" }],
    nextSlug: "vaccination-guide",
    image: "photo-1454165804606-c3d57bc86b40",
  }),
  G({
    slug: "vaccination-guide",
    icon: "Syringe",
    category: "docs",
    titleBn: "টিকা গাইড",
    titleEn: "Vaccination Guide",
    summaryBn: "সৌদি আরবের প্রয়োজনীয় টিকা।",
    summaryEn: "Required vaccines for Saudi travel.",
    explanationBn: "মেনিনজাইটিসসহ সিজনাল নির্দেশনা অনুসরণ করুন। টিকা কার্ড সাথে রাখুন।",
    explanationEn: "Follow meningitis and seasonal requirements. Carry your vaccine card.",
    stepsBn: ["তালিকা দেখুন", "কেন্দ্রে টিকা", "সার্টিফিকেট", "অ্যাপ আপলোড"],
    stepsEn: ["Check list", "Vaccinate", "Certificate", "App upload"],
    doBn: ["আগেভাগে টিকা", "ডিজিটাল কপি"],
    doEn: ["Vaccinate early", "Digital copy"],
    dontBn: ["মেয়াদোত্তীর্ণ সার্টিফিকেট", "ভুয়া কাগজ"],
    dontEn: ["Expired certificates", "Fake documents"],
    faqs: [{ q: "কোভিড টিকা?", a: "নিয়ম পরিবর্তনশীল — সর্বশেষ সৌদি/বিমান নির্দেশনা দেখুন।" }],
    nextSlug: "what-is-ihram",
    image: "photo-1584515933487-779824d29309",
  }),
];

export function getGuide(slug: string): GuideContent | undefined {
  return GUIDES.find((g) => g.slug === slug);
}

export function getRelatedGuides(slug: string, n = 4): GuideContent[] {
  const idx = GUIDES.findIndex((g) => g.slug === slug);
  if (idx < 0) return GUIDES.slice(0, n);
  const rest = [...GUIDES.slice(idx + 1), ...GUIDES.slice(0, idx)];
  return rest.slice(0, n);
}
